### ISSUE TITLE
Support "Go to definition" for Elixir source code

### ISSUE THREAD

**Issue by thienlhh** [JakeBecker/vscode-elixir-ls#123]
This extension works well in almost features. Except I can not jump to Elixir source code it self by using Go to definition, although when I hover on the modules or functions it does show the documentations.

I'm using:
- Mac OSX
- Elixir 1.7.4 Erlang/OTP 21
- VSCode 1.30.2

**Comment by arthurborisow** [comment]
The same question here. Is it even possible to download the source code of dependencies of project to navigate to them?

**Comment by ppraisethesun** [comment]
This actually works on Manjaro linux with elixir installed using kiex.
On Mac OSXm however, I can't get it to work neither with asdf, nor with kiex

**Comment by jfhuete** [comment]
I have the same problem. Go to definition not work, but vscode detect all definitions in outline section of the sidebar.

I'm using:

Ubuntu 19.04
vscode 1.35.1
    * ElixirLS extension 0.2.25
Elixir 1.8.2
Earlang/OTP 22

**Comment by arthurborisow** [comment]
It actually works if elixir is built from sources, tanks @justincjohnson (https://github.com/elixir-lsp/elixir_sense/issues/44#issuecomment-524651802)

**Comment by tochukaso** [comment]
When I also built from source it worked. thanks @justincjohnson
I am using asdf. And I installed elixir using the below command
`$ asdf install elixir ref:07450832e7fbc902bfdee124adda1b5a0f6b689d ` 
I wanted to use elixir 1.10.1(OTP-22).

**Comment by alanvardy** [comment]
Hello!

I am not a maintainer of this project but would like to let you know that this repository has been inactive since May 2019. There is a fork that is being actively developed by community members, and I recommend you switch over!

The GitHub repository is here:
https://github.com/elixir-lsp/vscode-elixir-ls

And the Visual Studio Code extension is here:
https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

If you are having any issues or would like to open any pull requests, please try the new extension or clone the new repository first. You may find that the problem is already resolved 🙂

Thank you and happy Elixiring.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
