### ISSUE TITLE
Taskargs not being respected

### ISSUE THREAD

**Issue by abrarkhan1234** [JakeBecker/vscode-elixir-ls#158]
Debugger not respecting the `--no-halt` task arg when used with the run task.

I am attaching my configuration and you can see i am passing the arg. This works as expected when running the command in cli.
<img width="445" alt="Screenshot 2019-12-03 at 17 04 03" src="https://user-images.githubusercontent.com/6059489/70072545-1c09e900-15ef-11ea-8be4-dd1181bf2118.png">

**Comment by alanvardy** [comment]
Hello!

I am not a maintainer of this project but would like to let you know that this repository has been inactive since May 2019. There is a fork that is being actively developed by community members, and I recommend you switch over!

The GitHub repository is here:
https://github.com/elixir-lsp/vscode-elixir-ls

And the Visual Studio Code extension is here:
https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

If you are having any issues or would like to open any pull requests, please try the new extension or clone the new repository first. You may find that the problem is already resolved 🙂

Thank you and happy Elixiring.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
