### ISSUE TITLE
Snippets/code completion stop working when extension is enabled

### ISSUE THREAD

**Issue by mattbaker** [JakeBecker/vscode-elixir-ls#28]
This seems like an odd one. I'm finding that, when typing out a function, "tab" no longer autocompletes. In the past I've been able to type `def func() do`_tab_ and it would complete with the "end", yielding:

```elixir
def func() do
end
```

More things I've noticed:
 * With vscode-elixir installed and vscode-elixir-ls _not_ installed, this works
 * With vscode-elixir installed, and vscode-elixir-ls installed this stops working
 * With vscode-elixir not installed, and vscode-elixir-ls installed, this doesn't work

Any thoughts? I can't quite figure out what's going on and Google didn't turn anything up so I thought I'd come here.

Also, thanks for your work on ElixirLS, it's awesome and I love it.

**Comment by lleger** [comment]
I have the same issue.

**Comment by micahrye** [comment]
Same problem here. The debug feature of the project is great! but the code completion (IntelliSense) does not work as well as vscode-elixir. I have taken to disabling vscode-elixir-ls during normal development, since the code hints are so helpful, and enabling when I want to use the debugger.

I echo the above that this is a cool project and basically was the reason I started to use vscode, I hope it continues to develop.

**Comment by micahrye** [comment]
@mattbaker, I forget if you can edit the issue title or not, but if you can you might want to change the title name. I think "code hints broken" or "code completion broken" are more accurate. I know I did not look at this issue because I did not think it was relevant. I then spent a couple hours figuring out that it was the combination of "vscode-elixir" and "vscode-elixir-ls" that was breaking things. 

If you cannot change title it might be work creating another issue and reference this one.

**Comment by mattbaker** [comment]
Well, completion works, depending on how you define "completion." If I type `SomeModule.` VS Code will suggest functions in that module, and will autocomplete when I hit enter.

I'm not sure what the VS Code term for what I'm describing is — snippets maybe? Actually, now that I think about it, that might be the core of it. Maybe vscode-elixir is defining snippets and vscode-elixir-ls is somehow stepping on them 🤔 . 

I'll update the title to be a little more generic though, you raise a good point.

**Comment by samba6** [comment]
Look for this `vscode-elixir` setting

```json
"[elixir]":  {
    "editor.quickSuggestions": false
  }
```
And change it to

```json
"[elixir]":  {
    "editor.quickSuggestions": true
  }
```

There will now be two for every snippet, but that does no harm. All `vscode-elixir` features like intellisense work perfectly.

**Comment by micahrye** [comment]
@samba6 thanks, worked for me when I added your snippet to my settings.

**Comment by mattbaker** [comment]
Nice! @samba6 — how did you figure that out?

**Comment by samba6** [comment]
From the name of the setting: `editor.quickSuggestions`

**Comment by micahrye** [comment]
@mattbaker want to close.

**Comment by mattbaker** [comment]
Ah, I see, maybe this is as-designed: https://github.com/JakeBecker/vscode-elixir-ls/blob/ad43d134b3b00ee51363550b2ee1737371ee13db/CHANGELOG.md#v028-29-nov-2017

Curious what you think @JakeBecker.

**Comment by JakeBecker** [comment]
Sorry for the confusion, everyone. I got annoyed with the `editor.quickSuggestions` being on by default because it'd often trigger when ending a line with something like `do` or `else`, causing something other than a line break to be inserted. It'll still trigger automatically after a `.`, and you can trigger it manually with `Ctrl + Space`.

I can see why changing the default was confusing, so I added some text to the README to hopefully prevent future confusion: https://github.com/JakeBecker/vscode-elixir-ls/commit/3f8b64ac94d6c6cf81c1f8ac8e33a3adb8080180

**Comment by mattbaker** [comment]
Great, thanks!
