### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by emoragaf** [JakeBecker/vscode-elixir-ls#44]
it would be nice to have syntax highlighting of ExUnit commonly used "keywords" like  `test`, `setup` and the range of assertions

**Comment by JakeBecker** [comment]
I'm disinclined to do that because they're unavailable unless you've imported them, so they're not like the other "keywords" we highlight like `if` or `case`. It seems reasonable that a user might have a variable or function named `test` or `setup` in a non-test module, so I think better not to cause confusion by highlighting them as keywords. I'd rather stick to things defined in `Kernel` or `Kernel.SpecialForms`.
