### ISSUE TITLE
Discuss opinionated settings

### ISSUE THREAD

**Issue by maxmellen** [JakeBecker/vscode-elixir-ls#53]
Hi there 👋

I see you've documented the settings this extension sets by default for Elixir [in the README](https://github.com/JakeBecker/vscode-elixir-ls/blob/b574311e6cb338016c89e4947c2cc317d842995f/README.md#default-settings).
I really like that you admit how opinionated these are and immediately explain how to customize them for yourself.

A few things I'd like to note though:

- The list seems to be missing `"editor.wordBasedSuggestions": false` and `"editor.formatOnType": true`
- Do we still need to have `"editor.wordBasedSuggestions": false`?
  I feel like having `"editor.acceptSuggestionOnEnter": "off"` largely prevents this word based suggestions from being annoying while providing additional _dumber_ completion while the Elixir language server becomes smarter.
  For instance, right now, there is no _smart_ completion for atoms, and word base suggestions could nicely fill in while that's in the works 🙂

Best 🤗

**Comment by JakeBecker** [comment]
I think `"editor.wordBasedSuggestions": false` is a good default, just because autocomplete already seems to have a lot more suggestions than are actually useful most of the time and I don't want to further pollute the space of suggestions. Also, the server sorts the suggestions by type primarily instead of lexicographically, and so word-based suggestions generated by the client would either have to be prioritized ahead or behind all the server suggestions, and it seems like they'd end up either too aggressive or completely buried. It should be fairly easy to add any atoms appearing in a file to the server's autocomplete suggestions for it, and that's probably a better way to handle that if we think it'd be useful. I do agree I should add it to the readme though.

I left out `"editor.formatOnType": true` from the readme because I initially found the name totally misleading -- it sounds like it would run Elixir's formatter on your code, but really all it does is automatically close `do` or `fn ->` with an `end` for you. I left it out because I didn't want users to turn it off without knowing what it does, but in the interests of transparency and completeness I agree I should document it :)

**Comment by maxmellen** [comment]
I'll gladly PR the README change :)

**Comment by JakeBecker** [comment]
Okay!
