### ISSUE TITLE
Debugger attaching to running Elixir Process

### ISSUE THREAD

**Issue by cjimison** [JakeBecker/vscode-elixir-ls#76]
Sorry if this is a silly question but is there a way to attach the debugger to a running elixir project with your tool.  We have our own internal commands for loading up our source files via :int.i and the standard erlang :debugg.start works.  Just wondering if there was some magic foo I was missing to get a similar experience with VSCode.

Thanks!

**Comment by JakeBecker** [comment]
Not a silly question! Generally, the `"request"` field in `launch.json` will be either `launch` or `attach`, but ElixirLS only supports `launch` right now. Adding `attach` wouldn't be all that difficult, it would just involve adding configuration to connect to another erlang node instead of running a Mix task. I don't have immediate plans to implement it, but if you want to implement it, it wouldn't be all that code and I'd happily review a PR.

An easier option, though, might be to wrap whatever you have that launches your application in a Mix task, then debugging that. `:int.i` is a no-op if a file's already been interpreted, so it should be fine even if ElixirLS attempts to interpret your files again.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
