### ISSUE TITLE
Directory not being ignored by .gitignore file

### ISSUE THREAD

**Issue by rich-ware** [JakeBecker/vscode-elixir-ls#83]
Hi,

I am trying to get the .elixir_ls directory to be ignored by git. Unfortunately, it is not working for me. This is what I have in my .gitignore file: /.elixir_ls/**

I would appreciate the help so the .elixir_ls is not included in my git repo.

Thanks!

**Comment by JakeBecker** [comment]
You should be able to add just `.elixir_ls/` to your global gitignore file, usually `~/.gitignore`.

**Comment by zMeadz** [comment]
I am also not able to gitignore this directory. 

- Both the and global (```~/.gitignore```) and project  .gitignore include ```.elixir_ls/```.  (Also tried ```/.elixir_ls/```, ```/.elixir_ls/**```, ```/.elixir_ls/*```, ```/.elixir_ls```)
- Tried running ```git rm --cached .elixir_ls/ -r``` then committing the result
- Using VS Code, Github Desktop (both restarted)

**Comment by delameko** [comment]
I just have `.elixir_ls` in my global gitignore.  Make sure you actually have the global .gitignore configured in ~/.gitconfig.

    [core]
    excludesfile = /Users/<your username>/.gitignore

`/.elixir_ls/**` and `/.elixir_ls/*` are telling git to ignore the contents of the .elixir_ls folder, but not the folder itself, hence why it ignored the .gitignore you put inside.

**Comment by zMeadz** [comment]
@delameko Thanks for the response. Have implemented this, committed, and still no luck.

**Comment by blackbart420** [comment]
@zMeadz same thing for me, .elixir_ls is not ignored by git even though I put it in .gitignore
Did you find a trick to solve this?

**Comment by alanvardy** [comment]
Hello!

I am not a maintainer of this project but would like to let you know that this repository has been inactive since May 2019. There is a fork that is being actively developed by community members, and I recommend you switch over!

The GitHub repository is here:
https://github.com/elixir-lsp/vscode-elixir-ls

And the Visual Studio Code extension is here:
https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

If you are having any issues or would like to open any pull requests, please try the new extension or clone the new repository first. You may find that the problem is already resolved 🙂

Thank you and happy Elixiring.

**Comment by j-ornelas** [comment]
@zMeadz did you ever figure this out? still getting this issue after adding .elixir_ls/ to local and global .gitignores
