### ISSUE TITLE
Eval within deubgger

### ISSUE THREAD

**Issue by bcardarella** [JakeBecker/vscode-elixir-ls#88]
I know this is a known issue, as it is even noted in the debugger itself as a "soon" feature. As a matter of collaboration, @KronicDeth recently implemented this in IntelliJ https://www.youtube.com/watch?v=EDIPQUk_Ohc&feature=youtu.be

**Comment by KronicDeth** [comment]
The overall branch for all the debugger improvements is https://github.com/KronicDeth/intellij-elixir/tree/80.  The Evaluate support was done in these 4 commits:
1. [Show Elixir variables instead of Erlang variables](https://github.com/KronicDeth/intellij-elixir/commit/f5af1522f8f63094715bc687c5b2eab7bd334729)
2. [Evaluate Erlang variable in debugger](https://github.com/KronicDeth/intellij-elixir/commit/d9ea944e080c694f58035cdf64f3bdc970f45507)
3. [Evaluate Elixir code instead of Erlang code](https://github.com/KronicDeth/intellij-elixir/commit/76ea76ab4023a3f353eaf86c46aaf201f8c9434b)
4. [Remove need to pass variables back to Elixir node](https://github.com/KronicDeth/intellij-elixir/commit/872f07d1aa974f0b5e71b35c90aa2c7e2264bb8f)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
