### ISSUE TITLE
.formatter.exs files are not respected in multi-root workspaces

### ISSUE THREAD

**Issue by jdavis92** [JakeBecker/vscode-elixir-ls#91]
ElixirLS formats code as expected when only one Elixir project is open.  It doesn't appear to pick up the different `.formatter.exs` files in multi-root workspaces.

**Comment by JakeBecker** [comment]
Multi-root workspaces aren't really supported yet. It basically only uses the first project in your workspace, and everything outside of that is treated as not having a project (so no compilation, formatter.exs, etc).

Multi-root workspaces isn't a feature I've been using in VS Code, so it's a low priority for now, but something I should handle eventually. Happy to review PRs if anyone wants to tackle it.

**Comment by pragdave** [comment]
Do you have any idea how big a job this would be (hours/days/weeks/a lifetime of endless toil)?

I'd really like to see this added, and knowing an order of magnitude effort would help be decide on some options.

Cheers


Dave

**Comment by pragdave** [comment]
That is... I've offering to write a PR if someone could guide me.

Dave

**Comment by marceldegraaf** [comment]
I'm running into the same issue. Currently I have around 10 separate Elixir projects in a single workspace. Everything works beautifully, including Dialyzer output for each separate project. 

However, it seems the formatting step uses the default `mix format` settings instead of the `.formatter.exs` configuration that's set per project. This is especially annoying because our CI pipeline checks our Elixir formatting using the settings in `.formatter.exs`. This means most of my commits break the build because of formatting, unless I remember to manually run `mix format` from the project folder before committing.

Adding to @pragdave: I'd love to help out to get this fixed, given some rough estimate of the complexity.

**Comment by phaibin** [comment]
Some issue, I need to open backend and frontend projects as a workspace. Auto formatting will not find the .formatter.exs in backend project. Please fix this asap! Thanks!

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
